version: "3.8"
services:
  scheduler:  # docker compose up
    image: dask-scheduler-img
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: dask-scheduler --port 8786 --dashboard-address :8787
    ports:
      - "8786:8786"
      - "8787:8787"
    networks:
      - dasknet
    healthcheck:
      test: ["CMD", "bash", "-c", "ss -ltn | grep 8786 || exit 1"]
      interval: 5s
      retries: 5
    environment: {}

  worker: # docker compose up --scale worker=3
    image: dask-worker-img
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: sh -c "python -u /app/src/worker_entrypoint.py"
    depends_on:
      - scheduler
    networks:
      - dasknet
    environment:
      - SHARD_DIR=/data/shards
      - DASK_SCHEDULER_ADDRESS=tcp://scheduler:8786
    deploy:
      resources:
        limits:
          memory: 4G

  query:  # docker compose up
    image: dask-query-img
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: sh -c "uvicorn query.query_service:app --host 0.0.0.0 --port 8000"
    environment:
      - DASK_SCHEDULER_ADDRESS=tcp://scheduler:8786
    depends_on:
      - scheduler
      - worker
    networks:
      - dasknet
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data

networks:
  dasknet:
    driver: bridge
